import { skipOnboardingIfShown } from "./onboarding-helpers"
import { test, expect } from "@playwright/test"
import { readFileSync } from "node:fs"
import { parseEnv } from "node:util"
import { randomUUID } from "node:crypto"
import { createClient } from "@supabase/supabase-js"
import sharp from "sharp"

// Explicitly opt in. Never record traces/screenshots containing passwords or revealed API keys.
test.use({ trace: "off", screenshot: "off", video: "off" })
test("hosted settings lifecycle on a disposable account", async ({ page, request }) => {
  test.skip(process.env.RUN_HOSTED_SETTINGS !== "true", "Opt in to the dedicated hosted settings test.")
  test.setTimeout(240_000)
  const env = parseEnv(readFileSync(".env", "utf8"))
  if (!env.SUPABASE_SECRET_KEY || !env.HOSTED_TEST_PROJECT_REF || env.HOSTED_TEST_PROJECT_REF !== env.SUPABASE_PROJECT_REF ||
    env.NEXT_PUBLIC_SUPABASE_URL !== `https://${env.HOSTED_TEST_PROJECT_REF}.supabase.co`) throw new Error("Dedicated hosted test target must be explicitly configured.")
  const admin = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SECRET_KEY, { auth: { persistSession: false, autoRefreshToken: false } })
  const email = `settings-${randomUUID()}@example.invalid`
  const initialPassword = `Start-${randomUUID()}!`
  const newPassword = `Updated-${randomUUID()}!`
  const created = await admin.auth.admin.createUser({ email, password: initialPassword, email_confirm: true, user_metadata: { full_name: "Settings Test" } })
  if (created.error || !created.data.user) throw new Error("Could not create the disposable settings fixture.")
  const userId = created.data.user.id
  const browserErrors: string[] = []
  page.on("pageerror", (error) => browserErrors.push(error.message))
  page.on("console", (message) => {
    if (message.type() === "error" && !message.text().includes("Failed to load resource")) browserErrors.push(message.text())
  })
  let orgId: string | undefined
  try {
    const membership = await admin.from("organization_members").select("org_id").eq("user_id", userId).single()
    orgId = membership.data?.org_id
    expect(Boolean(orgId)).toBe(true)
    await page.goto("/login")
    await page.getByLabel("Email address", { exact: true }).fill(email)
    await page.getByLabel("Password", { exact: true }).fill(initialPassword)
    await page.getByRole("button", { name: "Sign in", exact: true }).click()
    await skipOnboardingIfShown(page)
    await expect(page).toHaveURL(/\/dashboard$/)
    await page.getByRole("link", { name: "Settings", exact: true }).click()
    await expect(page.getByRole("tab", { name: "General", exact: true })).toHaveAttribute("aria-selected", "true")
    await expect(page.getByRole("tab")).toHaveText(["General", "Security", "Notifications", "Billing"])
    const settingsTab = await page.getByRole("tab", { name: "General", exact: true }).boundingBox()
    expect(settingsTab!.width).toBeLessThan(130)
    await page.getByRole("link", { name: "Workspace", exact: true }).click()
    await expect(page.getByRole("tab")).toHaveText(["General", "Team", "Advanced"])
    expect((await page.getByRole("tablist").boundingBox())!.width).toBeLessThan(340)
    await page.getByRole("link", { name: "Settings", exact: true }).click()
    await page.getByLabel("Full name", { exact: true }).fill("Alex Morgan")
    await page.getByRole("button", { name: "Save changes" }).click()
    await expect(page.getByRole("status")).toContainText("Profile saved")
    const avatar = await sharp({ create: { width: 64, height: 64, channels: 3, background: "#52665a" } }).png().toBuffer()
    await page.getByLabel("Profile photo file").setInputFiles({ name: "avatar.png", mimeType: "image/png", buffer: avatar })
    await expect(page.getByRole("status").filter({ hasText: "Profile photo updated" })).toBeVisible()
    await expect(page.getByRole("button", { name: "Remove", exact: true })).toBeVisible()
    await expect.poll(() => page.locator('img[data-slot="avatar-image"]').evaluateAll(images => images.length > 0 && images.every(image => (image as HTMLImageElement).naturalWidth > 0))).toBe(true)
    await page.screenshot({ path: "test-results/settings-general.png", fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: "test-results/settings-mobile.png", fullPage: true })
    await page.setViewportSize({ width: 1440, height: 1000 })
    await page.getByRole("link", { name: "Settings", exact: true }).click()
    await page.getByRole("tab", { name: "Security", exact: true }).click()
    await page.getByRole("button", { name: "Change password", exact: true }).click()
    await expect(page).toHaveURL(/\/dashboard\/account$/)
    await expect(page.getByRole("link", { name: "Return to workspace" })).toHaveCount(0)
    await page.screenshot({ path: "test-results/settings-security.png", fullPage: true })
    await page.getByLabel("Current password", { exact: true }).fill("An-incorrect-password")
    await page.getByLabel("New password", { exact: true }).fill(newPassword)
    await page.getByLabel("Confirm new password", { exact: true }).fill(newPassword)
    await page.getByRole("button", { name: "Update password", exact: true }).click()
    await expect(page.getByRole("tabpanel", { name: "Security" }).getByRole("alert")).toContainText("current password is incorrect")
    await page.getByLabel("Current password", { exact: true }).fill(initialPassword)
    await page.getByLabel("New password", { exact: true }).fill(newPassword)
    await page.getByLabel("Confirm new password", { exact: true }).fill(newPassword)
    await page.getByRole("button", { name: "Update password", exact: true }).click()
    await expect(page.getByRole("status")).toContainText("Password updated successfully")
    await expect(page.getByLabel("Current password", { exact: true })).not.toBeVisible()
    await page.getByRole("button", { name: "Account menu", exact: true }).click()
    await page.getByRole("menuitem", { name: "Sign out", exact: true }).click()
    await expect(page).toHaveURL(/\/login$/)
    await page.getByLabel("Email address", { exact: true }).fill(email)
    await page.getByLabel("Password", { exact: true }).fill(newPassword)
    await page.getByRole("button", { name: "Sign in", exact: true }).click()
    await skipOnboardingIfShown(page)
    await expect(page).toHaveURL(/\/dashboard$/)
    await page.getByRole("link", { name: "Settings", exact: true }).click()
    await page.getByRole("link", { name: "Integrations", exact: true }).click()
    await expect(page.getByRole("tab", { name: "API keys", exact: true })).toHaveAttribute("aria-selected", "true")
    await expect(page.getByRole("heading", { name: "Integrations", exact: true })).toBeVisible()
    await expect(page.getByRole("tab")).toHaveText(["API keys", "MCP"])
    await expect(page.getByRole("button", { name: "Copy MCP server URL", exact: true })).toHaveCount(0)
    await page.getByRole("tab", { name: "API keys", exact: true }).focus()
    await page.keyboard.press("ArrowRight")
    await page.keyboard.press("Enter")
    await expect(page.getByRole("tab", { name: "MCP", exact: true })).toHaveAttribute("aria-selected", "true")
    await expect(page.getByText("MCP (Model Context Protocol)", { exact: false })).toBeVisible()
    await expect(page.getByRole("heading", { name: "How to connect", exact: true })).toBeVisible()
    await expect(page.getByRole("button", { name: "Create API key", exact: true })).toHaveCount(0)
    await expect(page.getByRole("button", { name: "Copy API base URL", exact: true })).toHaveCount(0)
    await page.context().grantPermissions(["clipboard-read", "clipboard-write"])
    await page.getByRole("button", { name: "Copy MCP server URL", exact: true }).click()
    expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(new URL(env.APP_URL!).origin + "/api/mcp")
    expect(browserErrors).toEqual([])
    await page.screenshot({ path: "test-results/integrations-mcp.png", fullPage: true, animations: "disabled" })
    await page.setViewportSize({ width: 390, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.getByRole("button", { name: "Dark mode", exact: true }).click()
    await page.screenshot({ path: "test-results/integrations-mcp-mobile-dark.png", fullPage: true, animations: "disabled" })
    await page.getByRole("button", { name: "Light mode", exact: true }).click()
    await page.setViewportSize({ width: 1440, height: 1000 })
    await page.getByRole("button", { name: "Account menu", exact: true }).click()
    await page.getByRole("menuitem", { name: "Documentation", exact: true }).click()
    await expect(page).toHaveURL(/\/docs$/)
    await page.goto("/dashboard/account?tab=api-keys")
    await expect(page).toHaveURL(/\/dashboard\/integrations$/)
    await expect(page.getByRole("tab", { name: "API keys", exact: true })).toHaveAttribute("aria-selected", "true")
    await expect(page.getByText("GET returns workspace details.", { exact: false })).toHaveCount(0)
    await page.getByRole("button", { name: "Create API key", exact: true }).click()
    await page.getByLabel("Key name", { exact: true }).fill("Read-only test")
    await page.getByLabel("Expires in", { exact: true }).selectOption({ label: "Never" })
    await page.getByRole("button", { name: "Create key", exact: true }).click()
    await expect(page.getByRole("heading", { name: "Your API key is ready" })).toBeVisible()
    const readKey = await page.getByLabel("Your secret key").inputValue()
    await page.getByRole("button", { name: "Done", exact: true }).click()
    await expect(page.getByRole("row").filter({ hasText: "Read-only test" }).getByRole("cell").nth(3)).toHaveText("Never")
    await expect(page.getByRole("row").filter({ hasText: "Read-only test" })).toContainText("Active")
    const readResponse = await request.get("/api/v1/workspace", { headers: { Authorization: `Bearer ${readKey}` } })
    expect(readResponse.status()).toBe(200)
    expect((await readResponse.json()).data.id).toBe(orgId)
    expect((await request.patch("/api/v1/workspace", { headers: { Authorization: `Bearer ${readKey}` }, data: { name: "Not allowed" } })).status()).toBe(403)
    await page.getByRole("button", { name: "Revoke Read-only test", exact: true }).click()
    await page.getByRole("button", { name: "Revoke key", exact: true }).click()
    await expect(page.getByRole("status")).toContainText("API key revoked")
    await expect(page.getByRole("row").filter({ hasText: "Read-only test" })).toContainText("Revoked")
    expect((await request.get("/api/v1/workspace", { headers: { Authorization: `Bearer ${readKey}` } })).status()).toBe(401)
    await page.getByRole("button", { name: "Create API key", exact: true }).click()
    await page.getByLabel("Key name", { exact: true }).fill("Workspace automation")
    await page.getByLabel("Permissions", { exact: true }).selectOption("read_write")
    await page.getByLabel("Expires in", { exact: true }).selectOption({ label: "Never" })
    await page.getByRole("button", { name: "Create key", exact: true }).click()
    await expect(page.getByRole("heading", { name: "Your API key is ready" })).toBeVisible()
    const writeKey = await page.getByLabel("Your secret key").inputValue()
    await page.getByRole("button", { name: "Done", exact: true }).click()
    await expect(page.getByRole("row").filter({ hasText: "Workspace automation" })).toBeVisible()
    expect((await request.patch("/api/v1/workspace", { headers: { Authorization: `Bearer ${writeKey}` }, data: { name: "Settings fixture workspace" } })).status()).toBe(200)
    await page.screenshot({ path: "test-results/settings-api-keys.png", fullPage: true })
    await page.getByRole("link", { name: "Settings", exact: true }).click()
    await page.getByRole("tab", { name: "Security", exact: true }).click()
    await page.getByRole("button", { name: "Delete account", exact: true }).click()
    const dialog = page.getByRole("alertdialog")
    await expect(dialog.getByRole("button", { name: "Delete my account", exact: true })).toBeDisabled()
    await dialog.getByLabel("Current password", { exact: true }).fill(newPassword)
    await dialog.getByLabel("Type DELETE to confirm").fill("DELETE")
    await dialog.getByRole("button", { name: "Delete my account", exact: true }).click()
    await expect(page).toHaveURL(/\/login\?account=deleted$/)
    await expect(page.getByRole("status")).toContainText("Your account has been deleted")
    expect(Boolean((await admin.auth.admin.getUserById(userId)).error)).toBe(true)
    expect((await admin.from("organizations").select("id").eq("id", orgId!)).data).toEqual([])
    expect((await admin.storage.from("avatars").list(userId)).data).toEqual([])
    expect((await request.get("/api/v1/workspace", { headers: { Authorization: `Bearer ${writeKey}` } })).status()).toBe(401)
  } finally {
    // Scope cleanup exclusively to the account created in this test.
    await admin.storage.from("avatars").remove([`${userId}/avatar.webp`])
    const remaining = await admin.auth.admin.getUserById(userId)
    if (remaining.data.user) {
      const result = await admin.auth.admin.deleteUser(userId)
      if (result.error) throw new Error("Disposable settings account cleanup failed.")
    }
  }
})
