import { test, expect } from "@playwright/test"

test("theme selection slides, persists, and follows shared app layouts", async ({ page }) => {
  const errors: string[] = []
  page.on("pageerror", (error) => errors.push(error.message))
  page.on("console", (message) => {
    if (message.type() === "error") errors.push(message.text())
  })
  await page.goto("/login")
  const light = page.getByRole("button", { name: "Light mode", exact: true })
  const dark = page.getByRole("button", { name: "Dark mode", exact: true })
  const indicator = page.locator('[data-slot="theme-indicator"]')
  await expect(light).toHaveAttribute("aria-pressed", "true")
  await expect(light.locator("svg")).toBeVisible()
  await expect(dark.locator("svg")).toBeVisible()
  await indicator.evaluate((element) => {
    element.addEventListener("transitionrun", () => element.setAttribute("data-did-slide", "true"))
  })
  await dark.click()
  await expect(page.locator("html")).toHaveClass(/dark/)
  await expect(dark).toHaveAttribute("aria-pressed", "true")
  await expect(indicator).toHaveAttribute("data-did-slide", "true")
  await expect.poll(async () => {
    const marker = await indicator.boundingBox()
    const button = await dark.boundingBox()
    return Math.abs(marker!.x - button!.x)
  }).toBeLessThan(1)
  await dark.click()
  await expect(dark).toHaveAttribute("aria-pressed", "true")
  await page.reload()
  await expect(dark).toHaveAttribute("aria-pressed", "true")
  await expect(page.locator("html")).toHaveClass(/dark/)
  await page.getByRole("link", { name: "Create an account" }).click()
  await expect(dark).toHaveAttribute("aria-pressed", "true")
  for (const route of ["/forgot-password", "/verify-email", "/preview"]) {
    await page.goto(route)
    await expect(dark).toHaveAttribute("aria-pressed", "true")
  }
  await page.screenshot({ path: "test-results/theme-dark-desktop.png", fullPage: true })
  await light.click()
  await expect(page.locator("html")).toHaveClass(/light/)
  await light.click()
  await page.reload()
  await expect(light).toHaveAttribute("aria-pressed", "true")
  await expect.poll(() => page.evaluate(() => localStorage.getItem("theme"))).toBe("light")
  expect(errors).toEqual([])
})

test("system preference and changes in another tab update the slider", async ({ page, context }) => {
  await page.emulateMedia({ colorScheme: "dark" })
  await page.goto("/login")
  await page.evaluate(() => localStorage.setItem("theme", "system"))
  await page.reload()
  await expect(page.getByRole("button", { name: "Dark mode", exact: true })).toHaveAttribute("aria-pressed", "true")
  await page.emulateMedia({ colorScheme: "light" })
  await expect(page.getByRole("button", { name: "Light mode", exact: true })).toHaveAttribute("aria-pressed", "true")
  const other = await context.newPage()
  await other.goto("/preview")
  await other.getByRole("button", { name: "Dark mode", exact: true }).click()
  await expect(page.getByRole("button", { name: "Dark mode", exact: true })).toHaveAttribute("aria-pressed", "true")
  await expect(page.locator("html")).toHaveClass(/dark/)
  await other.close()
})

test("keyboard and mobile controls work with reduced motion", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: "reduce" })
  for (const route of ["/login", "/preview"]) {
    await page.goto(route)
    const light = page.getByRole("button", { name: "Light mode", exact: true })
    const dark = page.getByRole("button", { name: "Dark mode", exact: true })
    await expect(light).toBeEnabled()
    await light.focus()
    await expect(light).toBeFocused()
    await page.keyboard.press("Enter")
    await page.keyboard.press("Tab")
    await expect(dark).toBeFocused()
    await page.keyboard.press("Space")
    await expect(dark).toHaveAttribute("aria-pressed", "true")
    await expect(page.locator("html")).toHaveClass(/dark/)
    await expect(page.locator('[data-slot="theme-indicator"]')).toHaveCSS("transition-duration", "0s")
    await page.keyboard.press("d")
    await expect(light).toHaveAttribute("aria-pressed", "true")
    const left = await light.boundingBox()
    const right = await dark.boundingBox()
    expect(left!.y).toBe(right!.y)
    expect(left!.x + left!.width).toBeLessThanOrEqual(right!.x)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
})
