import { skipOnboardingIfShown } from "./onboarding-helpers"
import { test, expect, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { parseEnv } from 'node:util'
import { randomUUID } from 'node:crypto'
import { createClient, type SupabaseClient } from '@supabase/supabase-js'

test.use({trace:'off',screenshot:'off',video:'off',baseURL:'http://127.0.0.1:3000'})
async function login(page:Page,email:string,password:string) {
  await page.goto('/login')
  await page.getByLabel('Email address',{exact:true}).fill(email)
  await page.getByLabel('Password',{exact:true}).fill(password)
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await skipOnboardingIfShown(page)
  await expect(page).toHaveURL(/\/(dashboard|invite)$/)
}
function setup() {
  const env=parseEnv(readFileSync('.env','utf8'))
  if(!env.HOSTED_TEST_PROJECT_REF||env.HOSTED_TEST_PROJECT_REF!==env.SUPABASE_PROJECT_REF||env.NEXT_PUBLIC_SUPABASE_URL!==`https://${env.HOSTED_TEST_PROJECT_REF}.supabase.co`)throw Error('Explicit hosted target required')
  const admin=createClient(env.NEXT_PUBLIC_SUPABASE_URL!,env.SUPABASE_SECRET_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})
  return {env,admin}
}

test('workspace invitation verification, recovery, mismatch and email status',async({page,browser})=>{
  test.skip(process.env.RUN_HOSTED_WORKSPACES!=='true','Opt in to dedicated workspace lifecycle checks.')
  test.setTimeout(180_000)
  const {env,admin}=setup(),ids:string[]=[],contexts=[]
  const password=`Workspace-${randomUUID()}!`,email=`workspace-verify-${randomUUID()}@example.invalid`
  const ownerEmail=`workspace-mail-${randomUUID()}@example.invalid`
  const client=createClient(env.NEXT_PUBLIC_SUPABASE_URL!,env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})
  try {
    const owner=await admin.auth.admin.createUser({email:ownerEmail,password,email_confirm:true,user_metadata:{full_name:'Workspace Mail Check'}})
    if(owner.error)throw Error('Fixture account failed')
    ids.push(owner.data.user.id)
    if((await client.auth.signInWithPassword({email:ownerEmail,password})).error)throw Error('Fixture login failed')
    const target=(await client.from('organization_members').select('org_id').eq('user_id',ids[0]).single()).data!.org_id
    const invitation=await client.rpc('issue_workspace_invitation',{target,recipient:email,invited_role:'admin'})
    expect(Boolean(invitation.data?.token)).toBe(true)
    // Admin generateLink creates an unconfirmed signup without sending email or
    // changing the shared project's verification setting.
    const generated=await admin.auth.admin.generateLink({type:'signup',email,password,options:{data:{full_name:'Verified Invite',workspace_invitation:invitation.data.token}}})
    if(generated.error)throw Error('Verification fixture failed')
    ids.push(generated.data.user.id)
    expect(generated.data.user.email_confirmed_at).toBeFalsy()
    expect((await admin.from('organization_members').select('org_id').eq('user_id',ids[1])).data).toEqual([{org_id:target}])
    await page.goto('/login')
    await page.getByLabel('Email address',{exact:true}).fill(email)
    await page.getByLabel('Password',{exact:true}).fill(password)
    await page.getByRole('button',{name:'Sign in',exact:true}).click()
    await expect(page.getByRole('alert').filter({hasText:'Verify your email'})).toBeVisible()
    await page.goto(`/auth/confirm?type=email&token_hash=${generated.data.properties.hashed_token}`)
    await page.getByRole('button',{name:'Verify email and continue'}).click()
    await skipOnboardingIfShown(page)
    await expect(page).toHaveURL(/\/dashboard$/)
    expect((await page.context().cookies()).find(c=>c.name==='forma-workspace')?.value).toBe(target)
    // Recovery retains an outstanding existing-account invitation until explicit acceptance.
    const recoveryEmail=`workspace-recovery-${randomUUID()}@example.invalid`
    const recoveryUser=await admin.auth.admin.createUser({email:recoveryEmail,password,email_confirm:true,user_metadata:{full_name:'Recovery Invite'}})
    if(recoveryUser.error)throw Error('Recovery fixture failed')
    ids.push(recoveryUser.data.user.id)
    const recoveryInvite=await client.rpc('issue_workspace_invitation',{target,recipient:recoveryEmail,invited_role:'member'})
    const context=await browser.newContext({baseURL:'http://127.0.0.1:3000'});contexts.push(context)
    const recoveryPage=await context.newPage()
    await recoveryPage.goto(`/invite#token=${recoveryInvite.data.token}`)
    await expect(recoveryPage.getByRole('button',{name:'Sign in to accept'})).toBeVisible()
    const recovery=await admin.auth.admin.generateLink({type:'recovery',email:recoveryEmail})
    if(recovery.error)throw Error('Recovery link failed')
    await recoveryPage.goto(`/auth/confirm?type=recovery&token_hash=${recovery.data.properties.hashed_token}`)
    await recoveryPage.getByRole('button',{name:'Continue to reset password'}).click()
    await recoveryPage.getByLabel('New password',{exact:true}).fill(`${password}New`)
    await recoveryPage.getByLabel('Confirm new password',{exact:true}).fill(`${password}New`)
    await recoveryPage.getByRole('button',{name:'Update password',exact:true}).click()
    await expect(recoveryPage).toHaveURL(/\/invite$/)
    await recoveryPage.getByRole('button',{name:'Accept invitation'}).click()
    await skipOnboardingIfShown(recoveryPage)
    await expect(recoveryPage).toHaveURL(/\/dashboard$/)
    await login(page,ownerEmail,password)
    const wrong=await client.rpc('issue_workspace_invitation',{target,recipient:`mismatch-${randomUUID()}@example.invalid`,invited_role:'member'})
    await page.goto(`/invite#token=${wrong.data.token}`)
    await expect(page.getByRole('button',{name:'Switch account',exact:true})).toBeVisible()
    await expect(page.getByRole('button',{name:'Accept invitation'})).toHaveCount(0)
    await page.goto('/dashboard/workspace')
    await page.getByRole('tab',{name:'General'}).focus()
    await page.keyboard.press('ArrowRight')
    await page.keyboard.press('Enter')
    await expect(page.getByRole('tab',{name:'Team'})).toHaveAttribute('aria-selected','true')
    await page.getByRole('button',{name:'Invite member'}).click()
    const rejectedEmail=`rejected-${randomUUID()}@example.invalid`
    await page.getByRole('dialog').getByLabel('Email address').fill(rejectedEmail)
    await expect(page.getByRole('dialog').getByLabel('Role',{exact:true})).toHaveValue('member')
    await expect(page.getByRole('dialog').getByLabel('Role',{exact:true}).locator('option')).toHaveText(['Member','Admin'])
    await page.getByRole('dialog').getByLabel('Role',{exact:true}).selectOption('admin')
    await page.getByRole('button',{name:'Send invitation',exact:true}).click()
    await expect(page.getByRole('dialog').getByRole('alert')).toContainText('email could not be sent')
    expect((await client.rpc('workspace_team',{target})).data.invitations.find((i:{email:string})=>i.email===rejectedEmail)?.role).toBe('admin')
    await expect(page.getByRole('dialog').getByLabel('Role',{exact:true})).toHaveValue('admin')
    await page.getByRole('button',{name:'Cancel',exact:true}).click()
    await expect(page.getByText('Not sent',{exact:false})).toBeVisible()
    const failedRow=page.getByText('Not sent',{exact:false}).locator('../..')
    await failedRow.getByRole('button',{name:'Resend',exact:true}).click()
    await expect(page.getByRole('alert').filter({hasText:'Wait a minute'})).toBeVisible()
    await failedRow.getByRole('button',{name:'Revoke',exact:true}).click()
    await page.getByRole('dialog').getByRole('button',{name:'Confirm'}).click()
    await expect(page.getByText('Not sent',{exact:false})).toHaveCount(0)
    const recipient=process.env.WORKSPACE_DELIVERY_TEST_EMAIL
    if(recipient){
      await page.getByRole('button',{name:'Invite member'}).click()
      await page.getByRole('dialog').getByLabel('Email address').fill(recipient)
      await page.getByRole('button',{name:'Send invitation',exact:true}).click()
      await expect(page.getByRole('dialog')).toHaveCount(0)
      await expect(page.getByText('Invitation sent. Waiting for them to join.',{exact:true})).toBeVisible()
      const roster=await client.rpc('workspace_team',{target})
      const mail=roster.data.invitations.find((i:{email:string})=>i.email===recipient)
      expect(mail.send_status).toBe('accepted')
      // Only report the matching fixture message's delivery event, never content.
      const response=await fetch('https://api.resend.com/emails?limit=20',{headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`}})
      const sent=await response.json()
      const message=sent.data?.find((item:{to:string[],subject:string})=>item.to.includes(recipient)&&item.subject.includes('invited'))
      console.log('Invitation provider acceptance verified; latest matching delivery event:',message?.last_event||'not available')
      await client.rpc('revoke_workspace_invitation',{target,invitation_id:mail.id})
    }
  } finally {
    for(const context of contexts)await context.close()
    await client.auth.signOut()
    await cleanup(admin,ids)
  }
})
async function cleanup(admin:SupabaseClient,ids:string[]) {
  // Only delete workspaces owned by the disposable accounts this test created.
  for(const id of ids){
    const user=await admin.auth.admin.getUserById(id)
    // Unconfirmed invited fixtures may receive fallback workspaces during cleanup.
    // Auth deletion removes their sole-member workspaces without reauthentication.
    if(!user.data.user?.email_confirmed_at)continue
    const {data}=await admin.from('organization_members').select('org_id,organizations(name)').eq('user_id',id).eq('role','owner')
    for(const row of data||[]){
      const org=row.organizations as unknown as {name:string}
      const result=await admin.rpc('delete_workspace',{target:row.org_id,actor:id,confirmation:org.name})
      if(result.error)throw Error('Fixture workspace cleanup failed')
    }
  }
  for(const id of ids){const result=await admin.auth.admin.deleteUser(id);if(result.error)throw Error('Fixture account cleanup failed')}
}

test('workspace browser lifecycle: switching, invitations, roles, removal, deletion and fallback',async({page,browser})=>{
  test.skip(process.env.RUN_HOSTED_WORKSPACES!=='true','Opt in to dedicated workspace lifecycle checks.')
  test.setTimeout(300_000)
  const {env,admin}=setup(),ids:string[]=[]
  const suffix=randomUUID(),password=`Workspace-${randomUUID()}!`
  const ownerEmail=`workspace-owner-${suffix}@example.invalid`,peerEmail=`workspace-peer-${suffix}@example.invalid`,newEmail=`workspace-new-${suffix}@example.invalid`
  const clients:SupabaseClient[]=[]
  const contexts=[]
  try {
    for(const [email,name] of [[ownerEmail,'Workspace Owner'],[peerEmail,'Workspace Peer']]){
      const created=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:name}})
      if(created.error||!created.data.user)throw Error('Could not create workspace fixture')
      ids.push(created.data.user.id)
      const client=createClient(env.NEXT_PUBLIC_SUPABASE_URL!,env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})
      const result=await client.auth.signInWithPassword({email,password});if(result.error)throw Error('Fixture sign-in failed')
      clients.push(client)
    }
    const initial=await clients[0].from('organization_members').select('org_id').eq('user_id',ids[0]).single()
    const original=initial.data!.org_id
    await login(page,ownerEmail,password)
    await page.getByRole('button',{name:'Switch workspace',exact:true}).click()
    await page.getByRole('menuitem',{name:'Create workspace',exact:true}).click()
    await page.getByLabel('Workspace name',{exact:true}).fill('Workspace Browser Test')
    await page.getByRole('dialog').getByRole('button',{name:'Create workspace',exact:true}).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.getByRole('button',{name:'Switch workspace'})).toContainText('Workspace Browser Test')
    const rows=await clients[0].from('organizations').select('id,name')
    expect(rows.data?.length).toBe(2)
    const target=rows.data!.find(row=>row.name==='Workspace Browser Test')!.id
    await page.reload()
    await expect(page.getByRole('button',{name:'Switch workspace'})).toContainText('Workspace Browser Test')
    const cookie=(await page.context().cookies()).find(item=>item.name==='forma-workspace')!
    expect(cookie.httpOnly).toBe(true);expect(cookie.value).toBe(target)
    await page.getByRole('link',{name:'Workspace',exact:true}).click()
    await expect(page.getByRole('tab',{name:'General',exact:true})).toHaveAttribute('aria-selected','true')
    await page.getByLabel('Workspace name',{exact:true}).fill('Pinned form workspace')
    // Another browser tab switches the shared cookie. The old form must still target its rendered workspace.
    const second=await page.context().newPage()
    await second.goto('/dashboard')
    await second.getByRole('button',{name:'Switch workspace'}).click()
    await second.getByRole('menuitem').filter({hasText:"Workspace Owner's workspace"}).click()
    await expect(second.getByRole('button',{name:'Switch workspace'})).toContainText("Workspace Owner's workspace")
    await page.getByRole('button',{name:'Save workspace'}).click()
    await expect.poll(async()=> (await clients[0].from('organizations').select('name').eq('id',target).single()).data?.name).toBe('Pinned form workspace')
    expect((await clients[0].from('organizations').select('name').eq('id',original).single()).data?.name).toBe("Workspace Owner's workspace")
    await second.close()
    await page.getByRole('button',{name:'Switch workspace'}).click()
    await page.getByRole('menuitem').filter({hasText:'Pinned form workspace'}).click()
    await expect.poll(async()=>(await page.context().cookies()).find(c=>c.name==='forma-workspace')?.value).toBe(target)
    await page.goto('/dashboard/workspace')
    await expect(page.getByLabel('Workspace name',{exact:true})).toHaveValue('Pinned form workspace')
    await expect(page.getByLabel('Workspace identifier')).toHaveValue(/^WRK[A-Z0-9]{10}$/)
    await expect(page.getByLabel('Workspace identifier')).toHaveAttribute('readonly','')
    await expect(page.getByLabel('Workspace identifier')).toHaveClass(/bg-muted/)
    await expect(page.getByRole('button',{name:'Leave workspace',exact:true})).toHaveCount(0)
    await expect(page.getByRole('button',{name:'Delete workspace',exact:true})).toHaveCount(0)
    await page.getByRole('tab',{name:'Team'}).focus()
    await page.keyboard.press('ArrowRight')
    await page.keyboard.press('Enter')
    await expect(page.getByRole('tab',{name:'Advanced'})).toHaveAttribute('aria-selected','true')
    await expect(page.getByRole('heading',{name:'Danger zone'})).toBeVisible()
    await page.setViewportSize({width:390,height:844})
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
    await page.screenshot({path:'test-results/workspaces-advanced-mobile.png',fullPage:true,animations:'disabled'})
    await page.setViewportSize({width:1440,height:1000})
    await page.getByRole('button',{name:'Dark mode',exact:true}).click()
    await page.screenshot({path:'test-results/workspaces-advanced-dark.png',fullPage:true,animations:'disabled'})
    await page.getByRole('button',{name:'Light mode',exact:true}).click()
    await page.getByRole('button',{name:'Delete workspace',exact:true}).click()
    await expect(page.getByRole('dialog')).toContainText('Permanently delete Pinned form workspace')
    await page.getByRole('button',{name:'Cancel',exact:true}).click()
    await page.getByRole('button',{name:'Leave workspace',exact:true}).click()
    await expect(page.getByRole('dialog')).toContainText('Leaving as the only member deletes')
    await page.getByRole('button',{name:'Cancel',exact:true}).click()
    await page.getByRole('tab',{name:'Team',exact:true}).click()
    await expect(page.getByRole('button',{name:'Leave workspace',exact:true})).toHaveCount(0)
    await expect(page.getByRole('table',{name:'Workspace team'})).toBeVisible()

    const invite=await clients[0].rpc('issue_workspace_invitation',{target,recipient:peerEmail,invited_role:'admin'})
    expect(Boolean(invite.data?.token)).toBe(true)
    await page.reload()
    await page.getByRole('tab',{name:'Team'}).click()
    await page.getByLabel('Filter team status').selectOption('pending')
    expect((await clients[0].rpc('workspace_team',{target})).data.invitations.some((i:{id:string})=>i.id===invite.data.id)).toBe(true)
    await expect(page.getByRole('table')).toContainText(peerEmail)
    await expect(page.getByRole('table').getByRole('button',{name:/Manage/})).toHaveCount(0)
    await expect(page.getByRole('table').getByRole('button',{name:'Resend'})).toBeVisible()
    const peerContext=await browser.newContext({baseURL:'http://127.0.0.1:3000'});contexts.push(peerContext)
    const peerPage=await peerContext.newPage()
    await peerPage.goto(`/invite#token=${invite.data.token}`)
    await expect(peerPage.getByRole('heading',{name:'Join Pinned form workspace'})).toBeVisible()
    await peerPage.getByRole('button',{name:'Sign in to accept'}).click()
    await peerPage.getByLabel('Email address',{exact:true}).fill(peerEmail)
    await peerPage.getByLabel('Password',{exact:true}).fill(password)
    await peerPage.getByRole('button',{name:'Sign in',exact:true}).click()
    await expect(peerPage.getByRole('button',{name:'Accept invitation'})).toBeVisible()
    await peerPage.getByRole('button',{name:'Accept invitation'}).click()
    await skipOnboardingIfShown(peerPage)
    await expect(peerPage).toHaveURL(/\/dashboard$/)
    expect((await clients[1].from('organization_members').select('org_id').eq('user_id',ids[1])).data?.length).toBe(2)
    expect((await clients[1].from('organization_members').select('role').eq('org_id',target).eq('user_id',ids[1]).single()).data?.role).toBe('admin')
    await peerPage.goto('/dashboard/workspace')
    await peerPage.getByRole('tab',{name:'Advanced'}).click()
    await expect(peerPage.getByRole('button',{name:'Delete workspace',exact:true})).toHaveCount(0)
    await peerPage.getByRole('tab',{name:'Team'}).click()
    await expect(peerPage.getByRole('button',{name:'Invite member'})).toBeVisible()
    await expect(peerPage.getByRole('button',{name:'Manage Workspace Owner'})).toHaveCount(0)
    // Admins can issue either invitation role through the actual server action.
    for(const invitedRole of ['member','admin']) {
      const email=`admin-invites-${invitedRole}-${suffix}@example.invalid`
      await peerPage.getByRole('button',{name:'Invite member'}).click()
      await peerPage.getByRole('dialog').getByLabel('Email address').fill(email)
      await expect(peerPage.getByRole('dialog').getByLabel('Role',{exact:true})).toHaveValue('member')
      await expect(peerPage.getByRole('dialog').getByLabel('Role',{exact:true}).locator('option')).toHaveText(['Member','Admin'])
      await peerPage.getByRole('dialog').getByLabel('Role',{exact:true}).selectOption(invitedRole)
      await peerPage.getByRole('button',{name:'Send invitation',exact:true}).click()
      await expect(peerPage.getByRole('dialog').getByRole('alert')).toContainText('email could not be sent')
      await peerPage.getByRole('button',{name:'Cancel',exact:true}).click()
      const invitations=(await clients[1].rpc('workspace_team',{target})).data.invitations
      const issued=invitations.find((i:{email:string})=>i.email===email)
      expect(issued?.role).toBe(invitedRole)
      expect((await clients[1].rpc('revoke_workspace_invitation',{target,invitation_id:issued.id})).error).toBeNull()
    }

    const fresh=await clients[0].rpc('issue_workspace_invitation',{target,recipient:newEmail,invited_role:'member'})
    expect(Boolean(fresh.data?.token)).toBe(true)
    const freshContext=await browser.newContext({baseURL:'http://127.0.0.1:3000'});contexts.push(freshContext)
    const freshPage=await freshContext.newPage()
    await freshPage.goto(`/invite#token=${fresh.data.token}`)
    await freshPage.getByRole('button',{name:'Create account',exact:true}).click()
    await freshPage.getByLabel('Full name',{exact:true}).fill('Workspace New')
    await freshPage.getByLabel('Email address',{exact:true}).fill(newEmail)
    await freshPage.getByLabel('Password',{exact:true}).fill(password)
    await freshPage.getByRole('button',{name:'Create account',exact:true}).click()
    await skipOnboardingIfShown(freshPage)
    await expect(freshPage).toHaveURL(/\/dashboard$/,{timeout:30000})
    const accepted=await clients[0].rpc('workspace_team',{target})
    const newMember=accepted.data.members.find((m:{email:string})=>m.email===newEmail)
    expect(Boolean(newMember?.id)).toBe(true);ids.push(newMember.id)
    expect((await admin.from('organization_members').select('org_id').eq('user_id',newMember.id)).data).toEqual([{org_id:target}])
    await freshPage.goto('/dashboard/workspace')
    await freshPage.getByRole('tab',{name:'Team'}).click()
    await expect(freshPage.getByRole('button',{name:'Invite member'})).toHaveCount(0)
    await freshPage.getByRole('tab',{name:'Advanced'}).click()
    await freshPage.getByRole('button',{name:'Leave workspace',exact:true}).click()
    await freshPage.getByRole('dialog').getByRole('button',{name:'Confirm'}).click()
    await expect(freshPage.getByRole('button',{name:'Switch workspace'})).toContainText("Workspace New's workspace")
    const fallback=await admin.from('organization_members').select('org_id,role').eq('user_id',newMember.id)
    expect(fallback.data?.length).toBe(1);expect(fallback.data?.[0].org_id).not.toBe(target);expect(fallback.data?.[0].role).toBe('owner')

    await page.reload();await page.getByRole('tab',{name:'Team'}).click()
    await page.getByLabel('Filter team status').selectOption('pending')
    await expect(page.getByRole('table')).not.toContainText('Workspace Peer')
    await page.getByLabel('Filter team status').selectOption('active')
    await page.getByLabel('Search team').fill('Workspace Peer')
    await expect(page.getByRole('table')).toContainText('Workspace Peer')
    await expect(page.getByRole('table')).not.toContainText('Workspace Owner')
    await page.getByLabel('Search team').clear()
    await page.getByLabel('Filter team status').selectOption('all')
    await page.getByRole('button',{name:'Manage Workspace Peer'}).click()
    await page.getByRole('menuitem',{name:'Transfer ownership',exact:true}).click()
    await expect(page.getByRole('dialog')).toContainText('You will become an Admin')
    await page.getByRole('dialog').getByRole('button',{name:'Confirm'}).click()
    await expect(page.getByRole('button',{name:'Switch workspace'})).toContainText(/admin/i)
    await page.getByRole('tab',{name:'Advanced'}).click()
    await expect(page.getByRole('button',{name:'Delete workspace',exact:true})).toHaveCount(0)
    await expect(page.getByRole('button',{name:'Leave workspace',exact:true})).toBeEnabled()
    await peerPage.reload()
    await peerPage.getByRole('tab',{name:'Team'}).click()
    await peerPage.getByRole('button',{name:'Manage Workspace Owner'}).click()
    await peerPage.getByRole('menuitem',{name:'Transfer ownership',exact:true}).click()
    await peerPage.getByRole('dialog').getByRole('button',{name:'Confirm'}).click()
    await expect(peerPage.getByRole('dialog')).toHaveCount(0)
    await expect(peerPage.getByRole('button',{name:'Switch workspace'})).toContainText(/admin/i)
    await page.reload()
    await page.getByRole('tab',{name:'Advanced'}).click()
    await expect(page.getByRole('button',{name:'Leave workspace',exact:true})).toBeDisabled()
    await page.getByRole('tab',{name:'Team'}).click()
    await expect(page.getByRole('tab',{name:'Team'})).toHaveAttribute('aria-selected','true')
    await page.screenshot({path:'test-results/workspaces-team.png',fullPage:true,animations:'disabled'})
    await page.setViewportSize({width:390,height:844})
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
    const manageButton=await page.getByRole('button',{name:'Manage Workspace Peer'}).boundingBox()
    expect(manageButton!.x+manageButton!.width).toBeLessThanOrEqual(390)
    await page.screenshot({path:'test-results/workspaces-mobile.png',fullPage:true})
    await page.setViewportSize({width:1440,height:1000})
    await page.getByRole('button',{name:'Dark mode',exact:true}).click()
    await page.screenshot({path:'test-results/workspaces-dark.png',fullPage:true})
    await page.getByRole('button',{name:'Light mode',exact:true}).click()
    await page.getByRole('button',{name:'Manage Workspace Peer'}).click()
    await page.getByRole('menuitem',{name:'Revoke access',exact:true}).click()
    await page.getByRole('dialog').getByRole('button',{name:'Confirm'}).click()
    await expect(page.getByText(peerEmail,{exact:true})).toHaveCount(0)
    await peerPage.reload()
    await expect(peerPage.getByRole('button',{name:'Switch workspace'})).toContainText("Workspace Peer's workspace")
    const lastInvite=await clients[0].rpc('issue_workspace_invitation',{target,recipient:`last-pending-${suffix}@example.invalid`,invited_role:'member'})
    expect(Boolean(lastInvite.data?.token)).toBe(true)
    await page.reload()
    await page.getByRole('tab',{name:'Advanced'}).click()
    await page.getByRole('button',{name:'Leave workspace',exact:true}).click()
    await expect(page.getByRole('dialog')).toContainText('pending invitations')
    await page.getByLabel('Type Pinned form workspace to confirm').fill('Pinned form workspace')
    await page.getByLabel('Current password',{exact:true}).fill('wrong-password')
    await page.getByRole('dialog').getByRole('button',{name:'Confirm'}).click()
    await expect(page.getByRole('dialog').getByRole('alert')).toContainText('password is incorrect')
    await page.getByLabel('Current password',{exact:true}).fill(password)
    await page.getByRole('dialog').getByRole('button',{name:'Confirm'}).click()
    await skipOnboardingIfShown(page)
    await expect(page).toHaveURL(/\/dashboard$/)
    expect((await admin.from('organizations').select('id').eq('id',target)).data).toEqual([])
    expect((await clients[0].rpc('preview_workspace_invitation',{invitation_token:lastInvite.data.token})).data).toBeNull()
  } finally {
    for(const context of contexts)await context.close()
    // Recover the exact new fixture if a browser assertion failed after signup.
    const users=await admin.auth.admin.listUsers({page:1,perPage:1000})
    const newUser=users.data.users.find(user=>user.email===newEmail)
    if(newUser&&!ids.includes(newUser.id))ids.push(newUser.id)
    for(const client of clients)await client.auth.signOut()
    await cleanup(admin,ids)
  }
})
