"use client"
import Link from "next/link"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import type { AdminReport, AdminRow } from "@/lib/admin/server"
export const str = (v: unknown) => v === null || v === undefined || v === "" ? "—" : String(v)
const rec = (v: unknown): Record<string, unknown> => v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : {}
const list = (v: unknown): AdminRow[] => Array.isArray(v) ? v : []
function date(v: unknown) { if (!v) return "—"; const d = new Date(typeof v === "number" ? v * 1000 : String(v)); return Number.isNaN(d.getTime()) ? "—" : d.toLocaleString("en-US", { timeZone: "UTC", dateStyle: "medium", timeStyle: "short" }) }
function money(amount: unknown, currency: unknown = "usd", minor = true) { if (amount == null || !currency) return "Unknown"; const c = String(currency).toUpperCase(); try { const formatter = new Intl.NumberFormat("en-US", { style: "currency", currency: c, maximumFractionDigits: c === "USD" && !minor ? 4 : undefined }); const decimals = new Intl.NumberFormat("en-US", { style: "currency", currency: c }).resolvedOptions().maximumFractionDigits; return formatter.format(Number(amount) / (minor ? 10 ** (decimals ?? 2) : 1)) } catch { return "Unknown" } }
const columns: Record<string, [string, string][]> = {
  users: [["name", "Name"], ["email", "Email"], ["created_at", "Signed up"], ["verified", "Verified"], ["last_sign_in_at", "Last sign-in"], ["workspace_count", "Workspaces"], ["onboarding_status", "Onboarding"]],
  workspaces: [["name", "Workspace"], ["identifier", "Identifier"], ["owner", "Owner"], ["member_count", "Members"], ["plan", "Plan"], ["subscription_status", "Subscription"], ["created_at", "Created"], ["last_activity", "Last activity"]],
  subscriptions: [["workspace", "Workspace"], ["plan", "Plan"], ["interval", "Interval"], ["amount", "Recurring amount"], ["status", "Status"], ["period_end", "Period end"], ["cancel_at_period_end", "Canceling"], ["synced_at", "Last synchronized"]],
  usage: [["workspace", "Workspace"], ["requests", "Requests"], ["completed", "Completed"], ["credits", "Credits charged"], ["available", "Available"], ["reserved", "Reserved"], ["input_tokens", "Input tokens"], ["output_tokens", "Output tokens"], ["cost_usd", "Recorded cost"]],
  bugs: [["title", "Title"], ["submitter", "Submitter"], ["workspace", "Workspace"], ["created_at", "Submitted"]],
  features: [["title", "Title"], ["submitter", "Submitter"], ["workspace", "Workspace"], ["votes", "Votes"], ["created_at", "Submitted"]],
}
function value(row: AdminRow, key: string) {
  if (key.endsWith("_at") || ["period_end", "last_activity"].includes(key)) return date(row[key])
  if (key === "amount") return money(row[key], row.currency)
  if (key === "cost_usd") return money(row[key], "usd", false)
  if (typeof row[key] === "boolean") return row[key] ? "Yes" : "No"
  return str(row[key])
}
export function AdminFilters({ section, options }: { section: string; options: Record<string, string> }) {
  const router = useRouter()
  return <form className="flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); const params = new URLSearchParams(); for (const [key, value] of data) if (String(value)) params.set(key, String(value)); router.push(`${location.pathname}?${params}`) }}>
    {section !== "overview" && <label className="min-w-48 flex-1 space-y-1 text-xs text-muted-foreground">Search<Input name="q" defaultValue={options.q} placeholder={section === "users" ? "Name, email or ID" : "Search records"} maxLength={120} /></label>}
    <label className="space-y-1 text-xs text-muted-foreground">Period · UTC<select name="days" defaultValue={options.days || "30"} className="block h-9 rounded-md border bg-background px-3 text-sm text-foreground">{[7, 30, 90].map(n => <option key={n} value={n}>Last {n} days</option>)}</select></label>
    {section === "users" && <><label className="space-y-1 text-xs text-muted-foreground">Verification<select name="status" defaultValue={options.status || ""} className="block h-9 rounded-md border bg-background px-3 text-sm text-foreground"><option value="">All accounts</option><option value="verified">Verified</option><option value="unverified">Unverified</option></select></label><label className="space-y-1 text-xs text-muted-foreground">Onboarding<select name="category" defaultValue={options.category || ""} className="block h-9 rounded-md border bg-background px-3 text-sm text-foreground"><option value="">All</option>{["in_progress", "completed", "skipped"].map(v => <option key={v} value={v}>{v.replace("_", " ")}</option>)}</select></label><label className="flex h-9 items-center gap-2 text-sm"><input type="checkbox" name="dated" value="true" defaultChecked={options.dated === "true"} />Signed up in period</label></>}
    {section === "subscriptions" && <><label className="space-y-1 text-xs text-muted-foreground">Status<select name="status" defaultValue={options.status || ""} className="block h-9 rounded-md border bg-background px-3 text-sm text-foreground"><option value="">All statuses</option>{["active", "past_due", "canceled", "unpaid", "trialing", "paused", "incomplete", "none", "unknown"].map(s => <option key={s}>{s}</option>)}</select></label><label className="space-y-1 text-xs text-muted-foreground">Plan key<Input name="category" defaultValue={options.category} placeholder="All plans" className="w-32" /></label></>}
    {section === "features" && <label className="space-y-1 text-xs text-muted-foreground">Sort<select name="sort" defaultValue={options.sort || ""} className="block h-9 rounded-md border bg-background px-3 text-sm text-foreground"><option value="">Newest</option><option value="votes">Most voted</option></select></label>}
    {section === "subscriptions" && <><label className="space-y-1 text-xs text-muted-foreground">Interval<select name="interval" defaultValue={options.interval || ""} className="block h-9 rounded-md border bg-background px-3 text-sm text-foreground"><option value="">All</option><option value="month">Monthly</option><option value="year">Annual</option></select></label><label className="space-y-1 text-xs text-muted-foreground">Cancellation<select name="canceling" defaultValue={options.canceling || ""} className="block h-9 rounded-md border bg-background px-3 text-sm text-foreground"><option value="">All</option><option value="true">Scheduled</option><option value="false">Not scheduled</option></select></label></>}
    {section === "workspaces" && <><label className="space-y-1 text-xs text-muted-foreground">Plan key<Input name="category" defaultValue={options.category} placeholder="All plans" className="w-32" /></label><label className="space-y-1 text-xs text-muted-foreground">Subscription<select name="status" defaultValue={options.status || ""} className="block h-9 rounded-md border bg-background px-3 text-sm text-foreground"><option value="">All</option>{["none", "active", "past_due", "canceled", "unpaid", "trialing"].map(s => <option key={s}>{s}</option>)}</select></label><label className="flex h-9 items-center gap-2 text-sm"><input type="checkbox" name="active" value="true" defaultChecked={options.active === "true"} />Active in period</label></>}
    {options.tab && <input type="hidden" name="tab" value={options.tab} />}{options.workspace && <input type="hidden" name="workspace" value={options.workspace} />}
    <Button type="submit" variant="outline">Apply</Button>
  </form>
}
export function ReportTable({ section, report, options = {} }: { section: string; report: AdminReport; options?: Record<string, string> }) {
  const [selected, setSelected] = useState<AdminRow | null>(null)
  const rows = report.rows || []; const cols = columns[section] || []
  if (report.enabled === false) return <div className="rounded-xl border p-8 text-center"><h2 className="font-medium">{section === "usage" ? "AI usage is unavailable" : "Billing is not configured"}</h2><p className="mt-2 text-sm text-muted-foreground">This module is disabled or has not been installed.</p></div>
  const page = Number(report.page || 0)
  function pageHref(p: number) {
    const q = new URLSearchParams(options); q.set("page", String(p))
    let trail: string[] = []; try { const parsed: unknown = JSON.parse(options.trail || "[]"); if (Array.isArray(parsed)) trail = parsed.filter((v): v is string => typeof v === "string" && v.length < 512).slice(-100) } catch { /* Reset a malformed navigation trail. */ }
    if (p > page && report.next_cursor) { trail.push(options.cursor || ""); q.set("cursor", JSON.stringify(report.next_cursor)) }
    else if (p < page) { const previous = trail.pop(); if (previous) q.set("cursor", previous); else q.delete("cursor") }
    q.set("trail", JSON.stringify(trail)); return `?${q}`
  }
  return <div className="space-y-3"><div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/40"><tr>{cols.map(([key, label]) => <th key={key} className="whitespace-nowrap px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-b last:border-0 hover:bg-muted/30">{cols.map(([key], index) => <td key={key} className="max-w-64 truncate px-4 py-3" title={value(row, key)}>{index === 0 ? section === "users" || section === "workspaces" ? <Link prefetch={false} href={`/admin/${section}/${row.id}`} className="font-medium underline-offset-4 hover:underline">{value(row, key)}</Link> : <button className="font-medium underline-offset-4 hover:underline" onClick={() => setSelected(row)}>{value(row, key)}</button> : value(row, key)}</td>)}</tr>)}</tbody></table>{!rows.length && <div className="p-12 text-center text-sm text-muted-foreground">No records match these filters.</div>}</div>
    <div className="flex items-center justify-between text-xs text-muted-foreground"><span>Page {page + 1} · {rows.length} records</span><div className="flex gap-4">{page > 0 && <Link href={pageHref(page - 1)}>Previous</Link>}{report.has_more && <Link href={pageHref(page + 1)}>Next</Link>}</div></div>
    {selected && <Dialog open onOpenChange={open => { if (!open) setSelected(null) }}><DialogContent className="max-h-[85svh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{str(selected.title || selected.workspace)}</DialogTitle><DialogDescription>{section === "subscriptions" ? "Read-only subscription information" : section === "usage" ? "Usage and accounting totals" : "Customer feedback"}</DialogDescription></DialogHeader>
      <dl className="grid grid-cols-2 gap-4">{cols.slice(1).map(([key, label]) => <div key={key}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 break-words text-sm">{value(selected, key)}</dd></div>)}</dl>
      {selected.description != null && <p className="whitespace-pre-wrap break-words rounded-lg bg-muted p-4 text-sm">{str(selected.description)}</p>}
      {selected.user_id != null && <Link href={`/admin/users/${selected.user_id}`} className="text-sm underline">View submitter</Link>}
      {(selected.workspace_id || section === "usage") && <Link href={`/admin/workspaces/${selected.workspace_id || selected.id}`} className="text-sm underline">View workspace</Link>}
      {section === "subscriptions" && <><p className="text-xs text-muted-foreground">Customer {str(selected.customer_id)}<br />Subscription {str(selected.subscription_id)}<br />Application paid access: {selected.paid_access ? "Yes" : "No"}</p>{selected.customer_id != null && <a target="_blank" rel="noopener noreferrer" className="text-sm underline" href={`https://dashboard.stripe.com/${selected.mode === "test" ? "test/" : ""}customers/${encodeURIComponent(String(selected.customer_id))}`}>Open customer in Stripe</a>}<SubscriptionHistory id={selected.id} /></>}
      {section === "usage" && <p className="text-sm text-muted-foreground">Failed: {str(selected.failed)} · Stopped: {str(selected.stopped)} · Expired: {str(selected.expired)}<br />Requests with unknown cost: {str(selected.missing_cost)}</p>}
    </DialogContent></Dialog>}
  </div>
}
export function Overview({ report, days = "30" }: { report: AdminReport; days?: string }) {
  const billing = rec(report.billing), churn = rec(report.churn); const currencies = list(billing.currencies)
  const mrr = report.billing ? Number(billing.incomplete) > 0 ? "Incomplete" : currencies.length ? currencies.map(c => money(c.mrr_minor, c.currency)).join(" · ") : "0 · No recurring revenue" : "Unavailable"
  const cards = [["Signups", str(report.signups), "Accounts created in the period", "/admin/users?dated=true"], ["Active workspaces", str(report.active_workspaces), "Existing workspaces used in the period", "/admin/workspaces?active=true"], ["Monthly recurring revenue", mrr, "Latest synchronized monthly subscription value", "/admin/subscriptions"], ["Paid workspace churn", churn.rate == null ? str(churn.reason || "Insufficient history") : `${churn.rate}%`, `${str(churn.lost || 0)} lost of ${str(churn.starting || 0)} starting paid workspaces`, "/admin/subscriptions"]]
  return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, hint, href]) => <Link key={label} href={`${href}${href.includes("?") ? "&" : "?"}days=${days}`} className="rounded-xl border p-5 transition-colors hover:bg-muted/30"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-4 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-xs text-muted-foreground">{hint}</p></Link>)}</div>
    <p className="text-xs text-muted-foreground">{report.started_at ? `Activity recorded since ${date(report.started_at)} UTC. The current period is still in progress.` : "History begins when users sign in and use the application."} {Number(billing.incomplete) > 0 && `${billing.incomplete} subscription records need complete, current synchronization.`}</p>
    <div className="rounded-xl border p-5"><h2 className="font-medium">Account and workspace activity</h2><p className="mt-1 text-xs text-muted-foreground">Daily signups and active existing workspaces · UTC</p><div className="mt-6 h-64" role="img" aria-label="Daily signups and active workspace chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={list(report.series)}><CartesianGrid vertical={false} stroke="var(--border)" /><XAxis dataKey="day" tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} tick={{ fontSize: 11 }} /><Tooltip /><Area name="Signups" dataKey="signups" stroke="var(--foreground)" fill="var(--muted)" /><Area name="Active workspaces" dataKey="active_workspaces" stroke="var(--muted-foreground)" fill="transparent" /></AreaChart></ResponsiveContainer></div><details className="text-xs"><summary>View activity data</summary><ul className="mt-2 space-y-1">{list(report.series).map(r => <li key={str(r.day)}>{str(r.day)}: {str(r.signups)} signups, {str(r.active_workspaces)} active workspaces</li>)}</ul></details></div>
    {list(billing.series).length > 0 && <div className="rounded-xl border p-5"><h2 className="font-medium">Recorded MRR history</h2><ul className="mt-4 grid gap-2 text-sm sm:grid-cols-2">{list(billing.series).map(r => <li key={`${r.day}-${r.currency}`} className="flex justify-between gap-4"><span>{str(r.day)}</span><span>{r.complete ? money(r.mrr_minor, r.currency) : "Incomplete observation"}</span></li>)}</ul></div>}
    <details className="text-sm text-muted-foreground"><summary className="cursor-pointer">How these metrics work</summary><p className="mt-3">Churn measures starting paid workspaces that have canceled or become unpaid and remain lost at the end of the period. New subscriptions, scheduled cancellations and temporary payment retries do not count as churn. MRR includes active and past-due recurring subscriptions and normalizes annual prices. Unknown historical states are not shown as zero.</p></details></>
}
export function Detail({ section, report }: { section: string; report: AdminReport }) {
  const row = report.rows?.[0]
  if (!row) return <p className="text-muted-foreground">This record is no longer available.</p>
  return <><dl className="grid gap-5 rounded-xl border p-5 sm:grid-cols-2 lg:grid-cols-3">{(columns[section] || []).map(([key, label]) => <div key={key}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 break-words text-sm">{value(row, key)}</dd></div>)}</dl>
    {section === "users" && <div className="rounded-xl border p-5"><h2 className="font-medium">Onboarding answers</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2">{[["display_name", "Preferred name"], ["use_case", "Intended use"], ["interests", "Interests"]].map(([key, label]) => { const answer = rec(report.onboarding)[key]; return <div key={key}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 text-sm">{answer == null || answer === "" ? "Not provided" : Array.isArray(answer) ? answer.join(", ") || "Not provided" : str(answer)}</dd></div> })}</dl></div>}
    <div className="rounded-xl border p-5"><h2 className="font-medium">{section === "users" ? "Workspaces" : "Members"}</h2><ul className="mt-4 divide-y">{list(report.memberships || report.members).map(m => <li key={m.id} className="flex justify-between gap-4 py-3 text-sm"><Link href={`/admin/${section === "users" ? "workspaces" : "users"}/${m.id}`} className="truncate underline-offset-4 hover:underline">{str(m.name || m.email)}</Link><span className="text-muted-foreground">{str(m.role)}</span></li>)}</ul></div>
  </>
}
export function UsageSummary({ report }: { report: AdminReport }) { const s = rec(report.summary); return report.enabled === false ? null : <div className="rounded-xl border p-5"><p className="text-sm">{str(s.requests || 0)} requests · {str(s.completed || 0)} completed · {str(s.credits || 0)} credits charged · {money(s.cost_usd, "usd", false)} recorded cost</p><p className="mt-2 text-xs text-muted-foreground">{str(s.missing_cost || 0)} requests have unknown cost; {str(s.missing_tokens || 0)} have incomplete token counts. Recorded cost may differ from the provider invoice. Totals reflect retained records.</p></div> }
function SubscriptionHistory({ id }: { id: string }) {
  const [rows, setRows] = useState<AdminRow[] | null>(null), [error, setError] = useState(false)
  useEffect(() => { const controller = new AbortController(); fetch(`/api/admin?section=subscription-history&id=${encodeURIComponent(id)}`, { cache: "no-store", signal: controller.signal }).then(async r => { if (!r.ok) throw new Error(); setRows((await r.json()).rows) }).catch(() => { if (!controller.signal.aborted) setError(true) }); return () => controller.abort() }, [id])
  return <section className="space-y-2"><h3 className="text-sm font-medium">Recorded status history · latest 100 changes</h3>{error ? <p role="alert" className="text-xs text-destructive">History is unavailable. Reopen the details to retry.</p> : rows === null ? <p className="text-xs text-muted-foreground">Loading history…</p> : !rows.length ? <p className="text-xs text-muted-foreground">No history recorded yet.</p> : <ul className="space-y-2">{rows.map(r => <li key={r.id} className="text-xs">{date(r.observed_at)} UTC · {str(rec(r.state).status)}{r.gap_before === true && " · Gap in observations"}</li>)}</ul>}</section>
}
